### ISSUE TITLE
message cannot be changed from preprocess

### ISSUE THREAD

**Issue by benjamin-feron** [baryon/tracer#137] opened 2022-12-15 15:09 UTC
Hi,

In preprocess, ```data.message``` cannot be changed

### Code

```js
import tracer from 'tracer'

const logger = tracer.console({
  preprocess: data => {
    data.title = 'XXX'
    data.message = 'ZZZ'
  }
})

logger.debug('test')
```

### Output

```
2022-12-15T16:06:03+0100 <XXX> <anonymous>:30 () test
```

### Expected output

```
2022-12-15T16:06:03+0100 <XXX> <anonymous>:30 () ZZZ
```

### Test code

This code can be tested [here](https://playcode.io/1037395)

### Workaround

```js
data.args[0] = 'ZZZ'
```

**Comment by baryon** [comment] 2023-09-13 04:18
Of course! Here's the translation:

"The purpose of the `preprocess` function is to perform some operations before outputting the message. If you modify the `message` here, when calling `logger.debug('test')`, the `message` will be populated with "test". This is not a bug. Let's close this issue."

**Closed by baryon** 2023-09-13 04:18 UTC
